apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: k8s-multi-com-tls
spec:
  secretName: k8s-multi-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: k8smydomain.com
  dnsNames:
    - k8smydomain.com
    - www.k8smydomain.com
  acme: 
    config:
      - http01:
          ingressClass: nginx
        domains:
          - k8smydomain.com
          - www.k8smydomain.com
  